### ISSUE TITLE
Comment to a single photo follows no easy logic

### ISSUE THREAD

**Issue by rhisss** [buddydev/mediapress#35]
![untitled](https://cloud.githubusercontent.com/assets/3778500/13605518/e6418482-e56d-11e5-931d-8dc84735f004.PNG)
When a comment is made under a photo (an individual photo) in the activity stream by clicking the buddypress comment button it does not show up in that particular photo page. This is confusing as blog posts do not follow this behavior. 

I suggest - to test : post comment to a photo in the stream by clicking the buddypress comment button. Also make another different comment in the photo page containing one single photo.

There seems to be NO sync or logic to what is happening. Thanks for looking into the matter.

**Comment by sbrajesh** [comment]
Hi,
Thank you for posting.
1. There was an issue that we just fixed yesterday related to the visibility of comments on Single Media page. Can you please update to the current github version and check if it fixes.

Now, I will explain the logic behind comments:-
1. All the uploads done via activity or any activity published for gallery are considered gallery activity. So, even if there is only one media, It will appear ass gallery activity. Any comment on the activity item appears on single gallery activity( There was an issue withgh display, which was fixed yeaterday, available on the github repo but not on wp.org at the moment)

Now coming to your first image, It appears as a comment on the single media page. PLease check again after update.

I agree with your 2nd suggestion about comment on comment, can you please advise a better way? I will be happy to add it quickly.

Please update from github and let me know if the comments are visible or not?

Thank you
Brajesh

**Comment by rhisss** [comment]
I tried with the Master at github. Was that the right thing to do ?
I made a fresh install and still the issue persists.
- Comment made under the thumbnail using the comment button in the bp stream does not appear under the image/photo in that image/phot page
- Comment made under the actual image in the individual page does not appear under the stream thumbnail and does not increment the comment counter.

Please see the attached image, and please see how commenting works in bp in blog post.
If I am doing wrong, can someone help with a demo mediapress link where comment behavior of an individual blog post and photo./image are the same. Thanks
![untitled](https://cloud.githubusercontent.com/assets/3778500/13617940/5256a7ae-e5a7-11e5-9fea-879dd5be99c0.PNG)

**Comment by sbrajesh** [comment]
Can you please check your wall gallery activity. That comment is supposed to appear on wall gallery. Uploads are considered an activity of wall gallery.
